### ISSUE TITLE
Define popup location and orientation

### ISSUE THREAD

**Issue by highend** [LastLifeLeft/Inputify#8]
Hi,

I've stumbled upon a few other things (e.g. you've misspelled the preference group `Beahvior`, it's either `Behavior` (AE) or `Behaviour` (BE)) and you keyboard / mousehooks totally block other softwares like XMouseButtonControl (`https://www.highrez.co.uk/downloads/XMouseButtonControl.htm`).

I'll eventually open a few other issues about these things, but this one is about a feature request^^

Please allow us to define (in pixels, multi-monitor support would be nice, so negative ones should be possible) the start location where the keys / mouse clicks appear and the orientation to where they expand (left, right, up, down).

I often capture .gif animations from applications and to reduce the size of these .gifs it's necessary to capture only a specific part of the workspace (which is normally not the lower left side of my first screen)...

Thanks for considering this

**Comment by LastLifeLeft** [comment]
>keyboard / mousehooks totally block other softwares like XMouseButtonControl (`https://www.highrez.co.uk/downloads/XMouseButtonControl.htm`).

I'll try to see what I can do.

> Please allow us to define (in pixels, multi-monitor support would be nice, so negative ones should be possible) the start location where the keys / mouse clicks appear and the orientation to where they expand (left, right, up, down).
> I often capture .gif animations from applications and to reduce the size of these .gifs it's necessary to capture only a specific part of the workspace (which is normally not the lower left side of my first screen)...

Location is planned, see #3.
I tried movement in the other directions, and it doesn't look good : Horizontal movement adds major readability issues, so I won't implement it. I can add down movement though.

**Comment by LastLifeLeft** [comment]
Opened #10 for the bug, closing for duplication of #3.

**Comment by LastLifeLeft** [comment]
@highend I implemented popup location in the latest version, could you check if it works with multiple screen? I tried my best to support it, but I own only one monitor, so I can't test if it actually works (And open a new issue if anything is wrong).

**Comment by highend** [comment]
@LastLifeLeft 
Only a dual monitor setup here but v0.6 works fine with it. Really cool, thanks!
